version: '3'
services:

  nginx:
    restart: always
    build: ./dockerfiles/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/workspace/hexo_blog/blog:/var/www/blog"
      - "/etc/nginx:/etc/nginx"
      - "./nginx/hexo.conf:/etc/nginx/conf.d/hexo.conf"
    container_name: "hexo_nginx"

  nodejs:
    restart: always
    build: ./dockerfiles/nodejs
    ports:
      - "4000:4000"
    volumes:
      - "~/workspace/hexo_blog:/var/www/blog"
      - "/etc/localtime:/etc/localtime"
      - "~/.ssh/id_rsa:/root/.ssh/id_rsa"
    container_name: "hexo_nodejs"